import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skill from '../components/Skills'
import { JOB_TITLE } from '../utils/constants'

export default function Home() {
  return (
    <div>
      <Head>
        <title>{JOB_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skill />
      <Projects />
      <Contact />
    </div>
  )
}
